# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
hilighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jackson Couse
tagline:          'Made This'
description:      'Photographer, film maker, and editor from Ottawa, Canada. '
url:              http://couse.ca
baseurl:          '/'
paginate:         3

author:
  name:           'Jackson Couse'
  url:            https://twitter.com/jacksoncouse

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/jacksoncouse
