# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jackson Couse
tagline:          'Photographer, artist, documentarian, teacher. Ottawa, Canada'
description:      'Artist, documentarian, and teacher from Ottawa, Canada. '
url:              http://couse.ca
baseurl:          '/'
paginate:         5

author:
  name:           'Jackson Couse'
  url:            https://twitter.com/jacksoncouse

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/jacksoncouse
