# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jackson Couse
tagline:          'Artist, Editor, Educator.'
description:      'I am an artist, publisher and documentarian. I make photographs, prints, books, videos, interventions, and collaborations. This is my website. '
url:              http://jacksoncouse.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Jackson Couse'
  url:            https://twitter.com/jacksoncouse

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jacksoncouse/jacksoncouse.github.io
