# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jackson Couse
tagline:          ''
description:      'Portfolio and archive of Jackson Couse: artist, documentarian, technologist, and teacher from Ottawa, Canada. '
url:              http://couse.ca
baseurl:          '/'
paginate:         5

author:
  name:           'Jackson Couse'
  url:            https://twitter.com/jacksoncouse

# Custom vars
version:          1.0.0

github:           https://github.com/jacksoncouse
  repo:           https://github.com/jacksoncouse/jacksoncouse.github.io
