# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            jacksoncouse.com
tagline:          'by Jackson Couse'
description:      'Portfolio and archive of Jackson Couse: photographer, artist, editor, educator, and publisher from Ottawa, Canada. '
url:              http://jacksoncouse.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Jackson Couse'
  url:            https://twitter.com/jacksoncouse

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jacksoncouse/jacksoncouse.github.io
